name: Quality Gate

on:
  pull_request:
    branches: [ '**' ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linting
        run: node scripts/ci/run-lint.js

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: node scripts/ci/run-tests.js

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build project
        run: node scripts/ci/run-build.js
